package cli

import (
	"errors"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/manjunathrathod/claude-repo-factory/internal/lang"
	"github.com/manjunathrathod/claude-repo-factory/internal/plugin"
	"github.com/manjunathrathod/claude-repo-factory/internal/prompt"
	"github.com/manjunathrathod/claude-repo-factory/internal/spec"
)

// Prompt messages are constants so tests can script answers against them
// without duplicating literals.
const (
	promptName        = "Repository name"
	promptDescription = "One line description"
	promptLanguage    = "Primary language"
	promptProjectType = "Project type"
	promptAuthor      = "Author"
	promptLicense     = "License"
)

// defaultDescription is offered when the user gives no description, so that
// --yes still produces a repository with a non-empty summary line.
const defaultDescription = "A repository generated by claude-repo-factory"

var licenseChoices = []prompt.Choice{
	{Value: "MIT", Label: "MIT"},
	{Value: "Apache-2.0", Label: "Apache 2.0"},
	{Value: "BSD-3-Clause", Label: "BSD 3-Clause"},
	{Value: spec.LicenseUnlicensed, Label: "None (proprietary)"},
}

type newOptions struct {
	dir          string
	language     string
	projectType  string
	description  string
	author       string
	license      string
	branch       string
	remote       string
	setOptions   []string
	acceptAll    bool
	skipGit      bool
	skipCI       bool
	skipDocs     bool
	skipWorkflow bool
}

const newLong = `Create a new repository configured for professional development and Claude Code.

The command resolves a repository specification from flags and, for anything
still missing, from interactive prompts. Pass --yes to accept every default
and run without prompting, which is what CI and scripts should do.

Repository generation is not implemented in this milestone: the command
resolves and validates the specification, then prints the plan it would
carry out.`

func newNewCommand(app *App) *cobra.Command {
	opts := &newOptions{}

	cmd := &cobra.Command{
		Use:     "new [name]",
		Short:   "Create a new repository configured for Claude Code",
		Long:    newLong,
		Args:    cobra.MaximumNArgs(1),
		Aliases: []string{"create"},
		RunE: func(cmd *cobra.Command, args []string) error {
			name := ""
			if len(args) == 1 {
				name = args[0]
			}
			return runNew(app, cmd, name, opts)
		},
	}

	f := cmd.Flags()
	f.StringVarP(&opts.language, "language", "l", "", "Primary language plugin (see: claude-repo-factory languages)")
	f.StringVarP(&opts.projectType, "type", "t", "", "Project type within the language, such as cli or service")
	f.StringVarP(&opts.dir, "dir", "d", "", "Directory to create the repository in (default: the repository name)")
	f.StringVar(&opts.description, "description", "", "One line description of the repository")
	f.StringVar(&opts.author, "author", "", "Author or owning team")
	f.StringVar(&opts.license, "license", "", "License identifier, or none")
	f.StringVar(&opts.branch, "branch", spec.DefaultBranch, "Initial branch name")
	f.StringVar(&opts.remote, "remote", "", "Git remote URL to register as origin")
	f.StringArrayVar(&opts.setOptions, "set", nil, "Language specific option as key=value (repeatable)")
	f.BoolVarP(&opts.acceptAll, "yes", "y", false, "Do not prompt; accept defaults for anything not given as a flag")
	f.BoolVar(&opts.skipGit, "no-git", false, "Do not initialise a Git repository")
	f.BoolVar(&opts.skipCI, "no-ci", false, "Do not generate GitHub Actions workflows")
	f.BoolVar(&opts.skipDocs, "no-docs", false, "Do not generate the docs structure")
	f.BoolVar(&opts.skipWorkflow, "no-claude-workflows", false, "Do not generate reusable Claude workflows")

	return cmd
}

func runNew(app *App, cmd *cobra.Command, name string, opts *newOptions) error {
	s, language, err := resolveSpec(app, name, opts)
	if err != nil {
		return err
	}

	out := cmd.OutOrStdout()
	if planErr := writePlan(out, s, language); planErr != nil {
		return planErr
	}

	_, err = language.Files(s)
	if errors.Is(err, plugin.ErrNotImplemented) {
		fmt.Fprintln(out)
		fmt.Fprintln(out, "Repository generation is not implemented yet.")
		fmt.Fprintln(out, "This milestone establishes the plugin contract, the CLI and the")
		fmt.Fprintln(out, "specification above; file generation lands in the next one.")
		return nil
	}
	return err
}

// resolveSpec layers flags and prompt answers over the factory defaults and
// validates the result, both generically and against the chosen plugin.
func resolveSpec(app *App, name string, opts *newOptions) (spec.Spec, plugin.Language, error) {
	s := spec.Default()
	asker := app.asker(opts.acceptAll)

	var err error
	if name == "" {
		name, err = asker.Input(promptName, "Used as the directory name and in generated documentation.", "")
		if err != nil {
			return s, nil, err
		}
	}
	s.Name = strings.TrimSpace(name)

	s.Description = opts.description
	if s.Description == "" {
		s.Description, err = asker.Input(promptDescription, "Shown at the top of README.md and CLAUDE.md.", defaultDescription)
		if err != nil {
			return s, nil, err
		}
	}

	language, err := resolveLanguage(app, asker, opts.language)
	if err != nil {
		return s, nil, err
	}
	desc := language.Descriptor()
	s.Language = desc.ID

	s.ProjectType, err = resolveProjectType(asker, desc, opts.projectType)
	if err != nil {
		return s, language, err
	}

	s.Author = opts.author
	if s.Author == "" {
		s.Author, err = asker.Input(promptAuthor, "Name or team recorded in the license and documentation.", "")
		if err != nil {
			return s, language, err
		}
	}

	s.License = opts.license
	if s.License == "" {
		s.License, err = asker.Select(promptLicense, "Choose none for proprietary code.", licenseChoices, "MIT")
		if err != nil {
			return s, language, err
		}
	}

	s.TargetDir = opts.dir
	if s.TargetDir == "" {
		s.TargetDir = s.Name
	}
	s.DefaultBranch = opts.branch
	s.Remote = opts.remote

	s.Features.Git = !opts.skipGit
	s.Features.GitHubActions = !opts.skipCI
	s.Features.Docs = !opts.skipDocs
	s.Features.ClaudeWorkflows = !opts.skipWorkflow

	if err := applySetOptions(&s, opts.setOptions); err != nil {
		return s, language, err
	}
	if err := resolveLanguageOptions(&s, asker, language); err != nil {
		return s, language, err
	}

	if err := s.Validate(); err != nil {
		return s, language, fmt.Errorf("invalid repository specification:\n%w", err)
	}
	if err := language.Validate(s); err != nil {
		return s, language, err
	}
	return s, language, nil
}

func resolveLanguage(app *App, asker prompt.Asker, flagValue string) (plugin.Language, error) {
	if flagValue != "" {
		l, err := app.Registry.Get(flagValue)
		if err != nil {
			return nil, err
		}
		if l.Descriptor().Status != plugin.StatusStable {
			return nil, fmt.Errorf("language %q is on the roadmap but not available yet", l.Descriptor().ID)
		}
		return l, nil
	}

	available := app.Registry.Available()
	if len(available) == 0 {
		return nil, errors.New("no language plugins are available in this build")
	}
	choices := make([]prompt.Choice, 0, len(available))
	for _, l := range available {
		d := l.Descriptor()
		choices = append(choices, prompt.Choice{Value: d.ID, Label: d.DisplayName + " - " + d.Summary})
	}
	picked, err := asker.Select(promptLanguage, "Determines the toolchain, standards and CI of the repository.", choices, choices[0].Value)
	if err != nil {
		return nil, err
	}
	return app.Registry.Get(picked)
}

func resolveProjectType(asker prompt.Asker, desc plugin.Descriptor, flagValue string) (string, error) {
	if flagValue != "" {
		if !desc.HasProjectType(flagValue) {
			return "", fmt.Errorf("unknown project type %q for %s (available: %s)",
				flagValue, desc.ID, strings.Join(desc.ProjectTypeIDs(), ", "))
		}
		return flagValue, nil
	}
	if len(desc.ProjectTypes) == 0 {
		return "", nil
	}

	choices := make([]prompt.Choice, 0, len(desc.ProjectTypes))
	for _, pt := range desc.ProjectTypes {
		choices = append(choices, prompt.Choice{Value: pt.ID, Label: pt.DisplayName + " - " + pt.Summary})
	}
	def := desc.DefaultProjectType
	if def == "" {
		def = desc.ProjectTypes[0].ID
	}
	return asker.Select(promptProjectType, "Shapes the generated layout and CI jobs.", choices, def)
}

// resolveLanguageOptions asks for the language-specific answers the selected
// plugin declares. The CLI knows nothing about what those answers mean.
func resolveLanguageOptions(s *spec.Spec, asker prompt.Asker, language plugin.Language) error {
	for _, opt := range lang.Options(language) {
		if strings.TrimSpace(s.Option(opt.Key, "")) != "" {
			continue
		}
		answer, err := asker.Input(opt.Prompt, opt.Help, opt.DefaultValue(*s))
		if err != nil {
			return err
		}
		s.SetOption(opt.Key, strings.TrimSpace(answer))
	}
	return nil
}

func applySetOptions(s *spec.Spec, pairs []string) error {
	for _, pair := range pairs {
		key, value, found := strings.Cut(pair, "=")
		key = strings.TrimSpace(key)
		if !found || key == "" {
			return fmt.Errorf("invalid --set value %q: expected key=value", pair)
		}
		s.SetOption(key, strings.TrimSpace(value))
	}
	return nil
}

// asker returns the prompt implementation for this run. With --yes every
// unanswered question resolves to its default instead of blocking.
func (a *App) asker(acceptAll bool) prompt.Asker {
	if acceptAll {
		return &prompt.Scripted{UseDefaults: true}
	}
	return a.Asker
}
