package cli

import (
	"errors"
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/manjunathrathod/claude-repo-factory/internal/config"
	"github.com/manjunathrathod/claude-repo-factory/internal/filesystem"
	"github.com/manjunathrathod/claude-repo-factory/internal/lang"
	"github.com/manjunathrathod/claude-repo-factory/internal/plugin"
	"github.com/manjunathrathod/claude-repo-factory/internal/prompt"
)

// Prompt messages are constants so tests can script answers against them
// without duplicating literals.
const (
	promptName           = "Project name"
	promptDescription    = "Description"
	promptLanguage       = "Programming language"
	promptProjectType    = "Project type"
	promptPackageManager = "Package manager"
	promptOutputDir      = "Output directory"
	promptInitGit        = "Initialize Git?"
	promptIncludeClaude  = "Include Claude Code setup?"
	promptIncludeActions = "Include GitHub Actions?"
	promptConfirmCreate  = "Create this project?"
)

// defaultDescription is offered when the user gives no description, so that
// --yes still produces a repository with a non-empty summary line.
const defaultDescription = "A repository generated by claude-repo-factory"

type newOptions struct {
	dir            string
	language       string
	projectType    string
	packageManager string
	description    string
	author         string
	license        string
	branch         string
	remote         string
	setOptions     []string
	acceptAll      bool
	showPlan       bool
	skipGit        bool
	skipCI         bool
	skipClaude     bool
	skipDocs       bool
	skipWorkflow   bool

	// changed reports whether a flag was given explicitly. A boolean flag
	// cannot express "unset" through its value alone, so without this the
	// command could not tell --no-git=false from an absent --no-git, and
	// would either prompt for an answer already given or silently ignore it.
	changed func(name string) bool
}

// explicit reports whether the named flag was set on the command line. It
// treats a nil changed func as "nothing was set", which keeps newOptions
// usable in a test that constructs it directly.
func (o *newOptions) explicit(name string) bool {
	return o.changed != nil && o.changed(name)
}

const newLong = `Create a new repository configured for professional development and Claude Code.

The command resolves a project configuration from flags and, for anything
still missing, from interactive prompts. Every prompt has a flag equivalent,
so the command is fully scriptable; --yes accepts every default and never
prompts, which is what CI and scripts should do.

Answers are validated, printed as a summary and confirmed before anything
happens. On confirmation the repository directory is created inside the
output directory: --dir C:\Projects with the name payment-api creates
C:\Projects\payment-api, and git is initialised inside it unless --no-git
is given.

An existing empty directory is adopted; an existing non-empty one is refused
and left untouched. File generation is not implemented in this milestone, so
the directory is created and left empty.`

func newNewCommand(app *App) *cobra.Command {
	opts := &newOptions{}

	cmd := &cobra.Command{
		Use:     "create [name]",
		Short:   "Create a new repository configured for Claude Code",
		Long:    newLong,
		Args:    cobra.MaximumNArgs(1),
		Aliases: []string{"new"},
		RunE: func(cmd *cobra.Command, args []string) error {
			name := ""
			if len(args) == 1 {
				name = args[0]
			}
			opts.changed = cmd.Flags().Changed
			return runNew(app, cmd, name, opts)
		},
	}

	f := cmd.Flags()
	f.StringVarP(&opts.language, "language", "l", "", "Primary language plugin (see: claude-repo-factory languages)")
	f.StringVarP(&opts.projectType, "type", "t", "", "Project type: api, cli, library or worker")
	f.StringVar(&opts.packageManager, "package-manager", "", "Package manager for the language, such as npm, uv or maven")
	f.StringVarP(&opts.dir, "dir", "d", "", "Directory to create the repository inside; the project directory is made within it (default: the working directory)")
	f.StringVar(&opts.description, "description", "", "One line description of the repository")
	f.StringVar(&opts.author, "author", "", "Author or owning team")
	f.StringVar(&opts.license, "license", "", "License identifier, or none")
	f.StringVar(&opts.branch, "branch", config.DefaultBranch, "Initial branch name")
	f.StringVar(&opts.remote, "remote", "", "Git remote URL to register as origin")
	f.StringArrayVar(&opts.setOptions, "set", nil, "Language specific option as key=value (repeatable)")
	f.BoolVarP(&opts.acceptAll, "yes", "y", false, "Do not prompt; accept defaults for anything not given as a flag")
	f.BoolVar(&opts.showPlan, "plan", false, "Print the full generation plan, including artifacts and commands")
	f.BoolVar(&opts.skipGit, "no-git", false, "Do not initialise a Git repository")
	f.BoolVar(&opts.skipCI, "no-ci", false, "Do not generate GitHub Actions workflows")
	f.BoolVar(&opts.skipClaude, "no-claude", false, "Do not generate Claude Code configuration")
	f.BoolVar(&opts.skipDocs, "no-docs", false, "Do not generate the docs structure")
	f.BoolVar(&opts.skipWorkflow, "no-claude-workflows", false, "Do not generate reusable Claude workflows")

	return cmd
}

func runNew(app *App, cmd *cobra.Command, name string, opts *newOptions) error {
	cfg, language, err := resolveConfig(app, name, opts)
	if err != nil {
		return err
	}

	// Each step names its own error rather than reusing or shadowing the one
	// above: govet rejects the shadow and gocritic rejects the reassignment,
	// and distinct names are what the rest of this package already does.
	out := cmd.OutOrStdout()
	if opts.showPlan {
		if planErr := writePlan(out, cfg, language); planErr != nil {
			return planErr
		}
		fmt.Fprintln(out)
	}
	if summaryErr := writeSummary(out, cfg, language.Descriptor()); summaryErr != nil {
		return summaryErr
	}

	// The summary's Output Directory row is the parent, because that is the
	// question the user answered. The confirmation must not rely on them doing
	// the join in their head, so the actual target is stated here, immediately
	// above the prompt that authorises creating it.
	target, targetErr := cfg.ResolvedProjectDirectory()
	if targetErr != nil {
		return fmt.Errorf("resolve target directory: %w", targetErr)
	}
	fmt.Fprintf(out, "\nThe repository will be created at %s\n", target)

	confirmed, confirmErr := app.asker(opts.acceptAll).Confirm(promptConfirmCreate,
		"Creates the directory above. No files are written in this milestone.", true)
	if confirmErr != nil {
		return fmt.Errorf("confirm project creation: %w", confirmErr)
	}
	if !confirmed {
		fmt.Fprintln(out, "Cancelled. Nothing was created.")
		return nil
	}

	fmt.Fprintln(out, "Configuration accepted.")

	result, prepErr := app.Generator.Prepare(cmd.Context(), cfg, app.Registry)
	if prepErr != nil {
		return explainPrepareFailure(prepErr, cfg)
	}
	if result.Created {
		fmt.Fprintf(out, "Created %s\n", result.Path)
	} else {
		fmt.Fprintf(out, "Using existing empty directory %s\n", result.Path)
	}
	if result.GitInitialized {
		fmt.Fprintf(out, "Initialised an empty Git repository on branch %s\n", cfg.DefaultBranch)
	}

	// File generation is deliberately not wired up yet. Asking the plugin
	// keeps this honest: when Files stops returning ErrNotImplemented the
	// command will fail loudly here rather than silently doing nothing.
	if _, err := language.Files(cfg); err != nil && !errors.Is(err, plugin.ErrNotImplemented) {
		return err
	}
	fmt.Fprintln(out, "No files were written; template generation lands in the next milestone.")
	return nil
}

// explainPrepareFailure turns a workspace failure into a message that tells
// the user what to do about it. Refusing to overwrite is the failure a user is
// most likely to hit, and "not empty" alone does not say how to proceed.
func explainPrepareFailure(err error, cfg config.ProjectConfig) error {
	if !errors.Is(err, filesystem.ErrNotEmpty) {
		return err
	}
	return fmt.Errorf("%w\n\nThe factory never writes into a directory that already has content. Either:\n"+
		"  - choose a different name:      create <other-name> --dir %s\n"+
		"  - choose a different location:  create %s --dir <other-directory>\n"+
		"  - or empty the directory yourself and run the command again",
		err, quoteIfSpaced(cfg.OutputDirectory), cfg.ProjectName)
}

// quoteIfSpaced makes a suggested command copy-pasteable when the path needs
// quoting, and leaves it alone when it does not.
func quoteIfSpaced(path string) string {
	if path == "" {
		return "."
	}
	if strings.ContainsAny(path, " \t") {
		return `"` + path + `"`
	}
	return path
}

// resolveConfig layers flags and prompt answers over the factory defaults and
// validates the result, first against the language-agnostic rules and then
// against the chosen plugin.
func resolveConfig(app *App, name string, opts *newOptions) (config.ProjectConfig, plugin.Language, error) {
	cfg := config.Default()
	asker := app.asker(opts.acceptAll)

	var err error
	if name == "" {
		name, err = asker.Input(promptName, "Used as the directory name and in generated documentation.", "")
		if err != nil {
			return cfg, nil, err
		}
	}
	cfg.ProjectName = strings.TrimSpace(name)

	cfg.Description = opts.description
	if cfg.Description == "" {
		cfg.Description, err = asker.Input(promptDescription, "Shown at the top of README.md and CLAUDE.md.", defaultDescription)
		if err != nil {
			return cfg, nil, err
		}
	}

	language, err := resolveLanguage(app, asker, opts.language)
	if err != nil {
		return cfg, nil, err
	}
	desc := language.Descriptor()
	// Store the canonical id, never the alias the user typed: two spellings of
	// one language would break equality and plan output.
	cfg.Language = desc.ID

	cfg.ProjectType, err = resolveProjectType(asker, desc, opts.projectType)
	if err != nil {
		return cfg, language, err
	}

	cfg.PackageManager, err = resolvePackageManager(asker, desc, opts.packageManager)
	if err != nil {
		return cfg, language, err
	}

	cfg.OutputDirectory = opts.dir
	if cfg.OutputDirectory == "" {
		// The answer is the *parent*: the repository directory is named by
		// ProjectName and created inside it. The default must therefore be
		// "." and never ProjectName — offering the project name here would
		// resolve to <cwd>/<name> as the parent and nest the repository
		// inside a directory of its own name.
		cfg.OutputDirectory, err = asker.Input(promptOutputDir,
			"The directory to create the repository inside. "+cfg.ProjectName+
				" is created within it, so \".\" puts it in the working directory.",
			".")
		if err != nil {
			return cfg, language, err
		}
	}
	cfg.OutputDirectory = strings.TrimSpace(cfg.OutputDirectory)

	// Author and license are not among the questions the create flow asks, so
	// they are flag-only. An absent --license keeps the default from
	// config.Default rather than blanking it.
	cfg.Author = opts.author
	if opts.license != "" {
		cfg.License = opts.license
	}
	cfg.DefaultBranch = opts.branch
	cfg.Remote = opts.remote

	cfg.IncludeDocs = !opts.skipDocs
	cfg.IncludeClaudeWorkflows = !opts.skipWorkflow

	if err := resolveFeatures(&cfg, asker, opts); err != nil {
		return cfg, language, err
	}
	if err := applySetOptions(&cfg, opts.setOptions); err != nil {
		return cfg, language, err
	}
	if err := resolveLanguageOptions(&cfg, asker, language); err != nil {
		return cfg, language, err
	}

	// The registry is the catalog: support questions are answered by the
	// plugins actually registered in this build.
	if err := cfg.Validate(app.Registry); err != nil {
		return cfg, language, fmt.Errorf("invalid project configuration: %w", err)
	}
	if err := language.Validate(cfg); err != nil {
		return cfg, language, err
	}
	return cfg, language, nil
}

// resolveFeatures settles the three yes/no questions. Each is asked only when
// its --no-* flag was absent, so a flag always wins over a prompt and the two
// front doors stay equivalent.
//
// Turning Claude Code setup off takes the agents and workflows with it: they
// live inside .claude, so generating them without it would produce a directory
// the user explicitly declined.
func resolveFeatures(cfg *config.ProjectConfig, asker prompt.Asker, opts *newOptions) error {
	answers := []struct {
		flag    string
		message string
		help    string
		skip    bool
		target  *bool
	}{
		{"no-git", promptInitGit, "Runs git init and creates the first commit.", opts.skipGit, &cfg.InitializeGit},
		{"no-claude", promptIncludeClaude, "Generates CLAUDE.md and the .claude directory.", opts.skipClaude, &cfg.IncludeClaude},
		{"no-ci", promptIncludeActions, "Generates a GitHub Actions workflow that runs the checks.", opts.skipCI, &cfg.IncludeGitHubActions},
	}

	for _, a := range answers {
		if opts.explicit(a.flag) {
			*a.target = !a.skip
			continue
		}
		answer, err := asker.Confirm(a.message, a.help, *a.target)
		if err != nil {
			return err
		}
		*a.target = answer
	}

	if !cfg.IncludeClaude {
		cfg.IncludeClaudeAgents = false
		cfg.IncludeClaudeWorkflows = false
	}
	return nil
}

func resolveLanguage(app *App, asker prompt.Asker, flagValue string) (plugin.Language, error) {
	if flagValue != "" {
		l, err := app.Registry.Get(flagValue)
		if err != nil {
			return nil, err
		}
		if l.Descriptor().Status != plugin.StatusStable {
			return nil, fmt.Errorf("language %q is on the roadmap but not available yet", l.Descriptor().ID)
		}
		return l, nil
	}

	available := app.Registry.Available()
	if len(available) == 0 {
		return nil, errors.New("no language plugins are available in this build")
	}
	choices := make([]prompt.Choice, 0, len(available))
	for _, l := range available {
		d := l.Descriptor()
		choices = append(choices, prompt.Choice{Value: string(d.ID), Label: d.DisplayName + " - " + d.Summary})
	}
	picked, err := asker.Select(promptLanguage, "Determines the toolchain, standards and CI of the repository.", choices, choices[0].Value)
	if err != nil {
		return nil, err
	}
	return app.Registry.Get(picked)
}

func resolveProjectType(asker prompt.Asker, desc plugin.Descriptor, flagValue string) (config.ProjectType, error) {
	if flagValue != "" {
		pt, err := config.ParseProjectType(flagValue)
		if err != nil {
			return "", err
		}
		if !desc.HasProjectType(pt) {
			return "", fmt.Errorf("%s does not support project type %q (available: %s)",
				desc.ID, pt, config.JoinProjectTypes(desc.ProjectTypeIDs(), ", "))
		}
		return pt, nil
	}
	if len(desc.ProjectTypes) == 0 {
		return "", nil
	}

	choices := make([]prompt.Choice, 0, len(desc.ProjectTypes))
	for _, pt := range desc.ProjectTypes {
		choices = append(choices, prompt.Choice{Value: string(pt.ID), Label: pt.DisplayName + " - " + pt.Summary})
	}
	def := desc.DefaultProjectType
	if def == "" {
		def = desc.ProjectTypes[0].ID
	}
	picked, err := asker.Select(promptProjectType, "Shapes the generated layout and CI jobs.", choices, string(def))
	if err != nil {
		return "", err
	}
	return config.ProjectType(picked), nil
}

// resolvePackageManager picks the dependency tool. The valid set is ecosystem
// knowledge, so it comes from the plugin descriptor rather than from the CLI.
func resolvePackageManager(asker prompt.Asker, desc plugin.Descriptor, flagValue string) (config.PackageManager, error) {
	if flagValue != "" {
		pm := config.ParsePackageManager(flagValue)
		if !desc.HasPackageManager(pm) {
			return "", fmt.Errorf("%s does not support package manager %q (available: %s)",
				desc.ID, pm, config.JoinPackageManagers(desc.PackageManagers, ", "))
		}
		return pm, nil
	}
	if len(desc.PackageManagers) == 0 {
		return "", nil
	}
	// A language with one package manager has nothing to ask about.
	if len(desc.PackageManagers) == 1 {
		return desc.PackageManagers[0], nil
	}

	choices := make([]prompt.Choice, 0, len(desc.PackageManagers))
	for _, pm := range desc.PackageManagers {
		choices = append(choices, prompt.Choice{Value: string(pm), Label: string(pm)})
	}
	def := desc.DefaultPackageManager
	if def == "" {
		def = desc.PackageManagers[0]
	}
	picked, err := asker.Select(promptPackageManager, "Determines the lockfile and the install command in CI.", choices, string(def))
	if err != nil {
		return "", err
	}
	return config.PackageManager(picked), nil
}

// resolveLanguageOptions asks for the language-specific answers the selected
// plugin declares. The CLI knows nothing about what those answers mean.
func resolveLanguageOptions(cfg *config.ProjectConfig, asker prompt.Asker, language plugin.Language) error {
	for _, opt := range lang.Options(language) {
		if strings.TrimSpace(cfg.Option(opt.Key, "")) != "" {
			continue
		}
		answer, err := asker.Input(opt.Prompt, opt.Help, opt.DefaultValue(*cfg))
		if err != nil {
			return err
		}
		cfg.SetOption(opt.Key, strings.TrimSpace(answer))
	}
	return nil
}

func applySetOptions(cfg *config.ProjectConfig, pairs []string) error {
	for _, pair := range pairs {
		key, value, found := strings.Cut(pair, "=")
		key = strings.TrimSpace(key)
		if !found || key == "" {
			return fmt.Errorf("invalid --set value %q: expected key=value", pair)
		}
		cfg.SetOption(key, strings.TrimSpace(value))
	}
	return nil
}

// asker returns the prompt implementation for this run. With --yes every
// unanswered question resolves to its default instead of blocking.
func (a *App) asker(acceptAll bool) prompt.Asker {
	if acceptAll {
		return &prompt.Scripted{UseDefaults: true}
	}
	return a.Asker
}
