package lang

import (
	"github.com/manjunathrathod/claude-repo-factory/internal/config"
	"github.com/manjunathrathod/claude-repo-factory/internal/plugin"
)

// The languages below are declared but not yet implemented. They exist so
// that the roadmap is visible in `claude-repo-factory languages` and, more
// importantly, so that the shape of a future plugin is exercised by the
// registry and the CLI today.
//
// Promoting one of these is a local change: fill in Instruct, add the option
// specs, flip Status to plugin.StatusStable. No core code is touched.
func init() {
	for _, d := range plannedLanguages {
		register(d)
	}
}

var plannedLanguages = []*Definition{
	planned("dotnet", ".NET", "C# on .NET 9 with xUnit and Roslyn analyzers", []string{"csharp", "cs", "c#"}),
	planned("rust", "Rust", "Rust with clippy, rustfmt and cargo-deny", []string{"rs"}),
	planned("terraform", "Terraform", "Terraform modules with tflint, tfsec and Terratest", []string{"tf", "opentofu"}),
	planned("react", "React", "React single page app with Vite, TypeScript and Testing Library", []string{}),
	planned("nextjs", "Next.js", "Next.js App Router with TypeScript and Playwright", []string{"next"}),
}

// planned builds a placeholder definition. Its Validate rejects selection
// with a clear message, so a planned language can never be generated by
// accident.
func planned(id config.Language, display, summary string, aliases []string) *Definition {
	return &Definition{
		Meta: plugin.Descriptor{
			ID:          id,
			DisplayName: display,
			Summary:     summary,
			Aliases:     aliases,
			Status:      plugin.StatusPlanned,
		},
		Instruct: func(config.ProjectConfig) plugin.Instructions { return plugin.Instructions{} },
	}
}
